using System.Text.Json;
using PowerBase.Application.Reports;
using PowerBase.Domain.Constants;
using PowerBase.Domain.Entities;

namespace PowerBase.Application.Formulas;

/// <summary>
/// In-memory filtering and sorting for compute-on-read (formula) fields.
/// Formula fields have no physical column so cannot participate in SQL WHERE/ORDER BY.
/// This class is used by RunReportQueryHandler when formula fields appear in the active
/// filter tree or sort spec.
///
/// Limitation: formula conditions nested inside an OR group with physical conditions are
/// extracted and applied as additional top-level AND conditions (conservative but safe
/// for the overwhelming majority of filter configurations generated by the report UI).
/// </summary>
public static class FormulaFilterSorter
{
    // ── Public helpers ──────────────────────────────────────────────────────────

    /// <summary>
    /// Returns true if any node in the filter tree references a formula field.
    /// </summary>
    public static bool TreeContainsFormulaField(FilterGroup? tree, HashSet<long> formulaFids)
    {
        if (tree == null) return false;
        foreach (var node in tree.Nodes)
        {
            if (node.Condition != null && formulaFids.Contains(node.Condition.FieldId)) return true;
            if (node.Group != null && TreeContainsFormulaField(node.Group, formulaFids)) return true;
        }
        return false;
    }

    public static (FilterGroup? physical, FilterGroup? formulaTree)
        SplitFilterTree(FilterGroup? tree, HashSet<long> formulaFids)
    {
        if (tree == null) return (null, null);
        return SplitGroup(tree, formulaFids);
    }

    public static List<(IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed)>
        ApplyFormulaFilters(
            IEnumerable<(IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed)> pairs,
            FilterGroup formulaTree,
            IReadOnlyList<AppField> allFields)
    {
        var fieldLookup = allFields
            .Where(f => f.Fid.HasValue)
            .GroupBy(f => (long)f.Fid!.Value)
            .ToDictionary(g => g.Key, g => g.First());

        return pairs.Where(p => MatchesGroup(p, formulaTree, fieldLookup)).ToList();
    }
    
    private static bool MatchesGroup((IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed) p, FilterGroup group, Dictionary<long, AppField> fieldLookup)
    {
        if (group.Nodes.Count == 0) return true;
        
        if (group.Logic == "or")
        {
            return group.Nodes.Any(n => 
                n.Condition != null ? MatchesCondition(p, n.Condition, fieldLookup) : 
                n.Group != null ? MatchesGroup(p, n.Group, fieldLookup) : false);
        }
        else // and
        {
            return group.Nodes.All(n => 
                n.Condition != null ? MatchesCondition(p, n.Condition, fieldLookup) : 
                n.Group != null ? MatchesGroup(p, n.Group, fieldLookup) : false);
        }
    }

    /// <summary>
    /// Sorts all row-computed pairs in-memory using the full sort spec list.
    /// Resolves values from computed dict for formula fields, from the row dict for regular fields.
    /// </summary>
    public static List<(IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed)>
        ApplySort(
            IEnumerable<(IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed)> pairs,
            IReadOnlyList<SortSpec> sorts,
            IReadOnlyList<AppField> allFields)
    {
        if (sorts.Count == 0) return pairs.ToList();

        var fieldLookup = allFields
            .Where(f => f.Fid.HasValue)
            .GroupBy(f => (long)f.Fid!.Value)
            .ToDictionary(g => g.Key, g => g.First());

        IOrderedEnumerable<(IReadOnlyDictionary<string, object?>, IReadOnlyDictionary<long, object?>)>? ordered = null;

        foreach (var sort in sorts)
        {
            var fid = sort.FieldId;
            var desc = sort.Desc;
            fieldLookup.TryGetValue(fid, out var field);

            object? GetValue((IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed) p)
            {
                if (field != null && FormulaTypeMap.IsComputedField(field.TypeCode, field.Settings))
                    return p.Computed.TryGetValue(fid, out var cv) ? cv : null;
                if (fid == -1)
                    return p.Row.TryGetValue("PublicId", out var pv) ? pv : null;
                var colName = field != null && !string.IsNullOrWhiteSpace(field.PhysicalColumnName)
                    ? field.PhysicalColumnName
                    : (fid switch
                    {
                        1 => "CreatedOn",
                        2 => "ModifiedOn",
                        3 => "Id",
                        4 => "CreatedBy",
                        5 => "ModifiedBy",
                        _ => field?.Fid.HasValue == true ? PhysicalNaming.ColumnName(field.Fid.Value) : PhysicalNaming.ColumnName((int)fid)
                    });
                return p.Row.TryGetValue(colName, out var v) ? v : null;
            }

            if (ordered == null)
                ordered = desc ? pairs.OrderByDescending(GetValue, NullSafeComparer.Instance)
                               : pairs.OrderBy(GetValue, NullSafeComparer.Instance);
            else
                ordered = desc ? ordered.ThenByDescending(GetValue, NullSafeComparer.Instance)
                               : ordered.ThenBy(GetValue, NullSafeComparer.Instance);
        }

        return ordered?.ToList() ?? pairs.ToList();
    }

    // ── Private ─────────────────────────────────────────────────────────────────

    private static (FilterGroup? physical, FilterGroup? formula) SplitGroup(FilterGroup group, HashSet<long> formulaFids)
    {
        var physicalNodes = new List<FilterNode>();
        var formulaNodes = new List<FilterNode>();

        if (group.Logic == "and")
        {
            foreach (var node in group.Nodes)
            {
                if (node.Condition != null)
                {
                    if (formulaFids.Contains(node.Condition.FieldId))
                        formulaNodes.Add(node);
                    else
                        physicalNodes.Add(node);
                }
                else if (node.Group != null)
                {
                    var (p, f) = SplitGroup(node.Group, formulaFids);
                    if (p != null) physicalNodes.Add(new FilterNode { Group = p });
                    if (f != null) formulaNodes.Add(new FilterNode { Group = f });
                }
            }
        }
        else // or
        {
            // For OR, if any node is a formula node (or contains one), we must evaluate the ENTIRE OR group in memory.
            // Why? Because A OR B cannot be split into SQL(A) AND Memory(B).
            if (TreeContainsFormulaField(group, formulaFids))
            {
                // The whole group goes to memory.
                formulaNodes.Add(new FilterNode { Group = group });
            }
            else
            {
                // The whole group goes to SQL.
                physicalNodes.Add(new FilterNode { Group = group });
            }
        }

        FilterGroup? physicalGroup = physicalNodes.Count > 0 ? new FilterGroup { Logic = "and", Nodes = physicalNodes } : null;
        if (group.Logic == "or" && physicalNodes.Count == 1 && physicalNodes[0].Group != null)
        {
            physicalGroup = physicalNodes[0].Group;
        }

        FilterGroup? formulaGroup = formulaNodes.Count > 0 ? new FilterGroup { Logic = "and", Nodes = formulaNodes } : null;
        if (group.Logic == "or" && formulaNodes.Count == 1 && formulaNodes[0].Group != null)
        {
            formulaGroup = formulaNodes[0].Group;
        }

        return (physicalGroup, formulaGroup);
    }

    private static bool MatchesCondition((IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed) p, FilterCondition c, Dictionary<long, AppField> fieldLookup)
    {
        fieldLookup.TryGetValue(c.FieldId, out var field);
        object? val = null;

        if (field != null && FormulaTypeMap.IsComputedField(field.TypeCode, field.Settings))
        {
            p.Computed.TryGetValue(c.FieldId, out val);
        }
        else if (c.FieldId == -1)
        {
            p.Row.TryGetValue("PublicId", out val);
        }
        else
        {
            var colName = field != null && !string.IsNullOrWhiteSpace(field.PhysicalColumnName)
                ? field.PhysicalColumnName
                : (c.FieldId switch
                {
                    1 => "CreatedOn",
                    2 => "ModifiedOn",
                    3 => "Id",
                    4 => "CreatedBy",
                    5 => "ModifiedBy",
                    _ => field?.Fid.HasValue == true ? PhysicalNaming.ColumnName(field.Fid.Value) : PhysicalNaming.ColumnName((int)c.FieldId)
                });
            p.Row.TryGetValue(colName, out val);
        }

        return c.Operator switch
        {
            "isEmpty"       => val is null || val.ToString() == string.Empty,
            "isNotEmpty"    => val is not null && val.ToString() != string.Empty,
            "eq"            => CompareValues(val, c.Value) == 0,
            "ne"            => CompareValues(val, c.Value) != 0,
            "gt"            => CompareValues(val, c.Value) > 0,
            "gte"           => CompareValues(val, c.Value) >= 0,
            "lt"            => CompareValues(val, c.Value) < 0,
            "lte"           => CompareValues(val, c.Value) <= 0,
            "contains"      => val?.ToString()?.Contains(c.Value ?? string.Empty, StringComparison.OrdinalIgnoreCase) == true,
            "notContains"   => val?.ToString()?.Contains(c.Value ?? string.Empty, StringComparison.OrdinalIgnoreCase) != true,
            "startsWith"    => val?.ToString()?.StartsWith(c.Value ?? string.Empty, StringComparison.OrdinalIgnoreCase) == true,
            "notStartsWith" => val?.ToString()?.StartsWith(c.Value ?? string.Empty, StringComparison.OrdinalIgnoreCase) != true,
            "date_eq"       => val is DateTime dt && DateTime.TryParse(c.Value, out var dv) && dt.Date == dv.Date,
            "in"            => ParseValueList(c.Value).Any(v => CompareValues(val, v) == 0),
            "notIn"         => !ParseValueList(c.Value).Any(v => CompareValues(val, v) == 0),
            _               => true,
        };
    }

    /// <summary>Mirrors RecordRepository.ParseValueList — the "in"/"notIn" wire format is a JSON
    /// string array in FilterCondition.Value, falling back to a comma split.</summary>
    private static List<string> ParseValueList(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return [];
        try
        {
            using var doc = JsonDocument.Parse(raw);
            if (doc.RootElement.ValueKind == JsonValueKind.Array)
            {
                var list = new List<string>();
                foreach (var el in doc.RootElement.EnumerateArray())
                {
                    var str = el.ValueKind == JsonValueKind.String ? el.GetString() : el.GetRawText();
                    if (!string.IsNullOrWhiteSpace(str)) list.Add(str.Trim('"'));
                }
                return list;
            }
        }
        catch (JsonException) { /* not JSON — fall through to comma split */ }
        return raw.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).ToList();
    }

    private static int CompareValues(object? a, string? b)
    {
        if (a is null && b is null) return 0;
        if (a is null) return -1;
        if (b is null) return 1;

        if (a is double d && double.TryParse(b, System.Globalization.NumberStyles.Any,
                System.Globalization.CultureInfo.InvariantCulture, out var db))
            return d.CompareTo(db);

        if (a is decimal dec && decimal.TryParse(b, out var decb))
            return dec.CompareTo(decb);

        if (a is DateTime dt && DateTime.TryParse(b, out var dtb))
            return dt.CompareTo(dtb);

        if (a is bool bl && bool.TryParse(b, out var blb))
            return bl.CompareTo(blb);

        return string.Compare(a.ToString(), b, StringComparison.OrdinalIgnoreCase);
    }
}

internal sealed class NullSafeComparer : IComparer<object?>
{
    public static readonly NullSafeComparer Instance = new();

    public int Compare(object? x, object? y)
    {
        if (x is null && y is null) return 0;
        if (x is null) return -1;
        if (y is null) return 1;
        if (x is IComparable cx)
        {
            try { return cx.CompareTo(y); }
            catch { /* type mismatch — fall through to string comparison */ }
        }
        return string.Compare(x.ToString(), y.ToString(), StringComparison.OrdinalIgnoreCase);
    }
}
