using System.Text.Json;
using PowerBase.Application.Reports;
using PowerBase.Domain.Constants;
using PowerBase.Domain.Entities;

namespace PowerBase.Application.Formulas;

/// <summary>
/// In-memory filtering and sorting for compute-on-read (formula) fields.
/// Formula fields have no physical column so cannot participate in SQL WHERE/ORDER BY.
/// This class is used by RunReportQueryHandler when formula fields appear in the active
/// filter tree or sort spec.
///
/// Limitation: formula conditions nested inside an OR group with physical conditions are
/// extracted and applied as additional top-level AND conditions (conservative but safe
/// for the overwhelming majority of filter configurations generated by the report UI).
/// </summary>
public static class FormulaFilterSorter
{
    // ── Public helpers ──────────────────────────────────────────────────────────

    /// <summary>
    /// Returns true if any node in the filter tree references a formula field.
    /// </summary>
    public static bool TreeContainsFormulaField(FilterGroup? tree, HashSet<long> formulaFids)
    {
        if (tree == null) return false;
        foreach (var node in tree.Nodes)
        {
            if (node.Condition != null && formulaFids.Contains(node.Condition.FieldId)) return true;
            if (node.Group != null && TreeContainsFormulaField(node.Group, formulaFids)) return true;
        }
        return false;
    }

    /// <summary>
    /// Removes nodes that reference formula fields from the tree (for SQL) and returns
    /// a flat list of the removed formula conditions (to be re-applied in-memory).
    /// The returned physical tree may be null when all nodes were formula conditions.
    /// </summary>
    public static (FilterGroup? physical, IReadOnlyList<FilterCondition> formulaConditions)
        SplitFilterTree(FilterGroup? tree, HashSet<long> formulaFids)
    {
        if (tree == null) return (null, []);
        var collected = new List<FilterCondition>();
        var physical = StripFormulaNodes(tree, formulaFids, collected);
        return (physical, collected);
    }

    /// <summary>
    /// Applies formula field conditions (extracted by SplitFilterTree) in-memory.
    /// All conditions are AND'd together on top of what SQL already filtered.
    /// </summary>
    public static List<(IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed)>
        ApplyFormulaFilters(
            IEnumerable<(IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed)> pairs,
            IReadOnlyList<FilterCondition> conditions)
    {
        if (conditions.Count == 0) return pairs.ToList();
        return pairs.Where(p => conditions.All(c => MatchesCondition(p.Computed, c))).ToList();
    }

    /// <summary>
    /// Sorts all row-computed pairs in-memory using the full sort spec list.
    /// Resolves values from computed dict for formula fields, from the row dict for regular fields.
    /// </summary>
    public static List<(IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed)>
        ApplySort(
            IEnumerable<(IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed)> pairs,
            IReadOnlyList<SortSpec> sorts,
            IReadOnlyList<AppField> allFields)
    {
        if (sorts.Count == 0) return pairs.ToList();

        var fieldLookup = allFields
            .Where(f => f.Fid.HasValue)
            .GroupBy(f => (long)f.Fid!.Value)
            .ToDictionary(g => g.Key, g => g.First());

        IOrderedEnumerable<(IReadOnlyDictionary<string, object?>, IReadOnlyDictionary<long, object?>)>? ordered = null;

        foreach (var sort in sorts)
        {
            var fid = sort.FieldId;
            var desc = sort.Desc;
            fieldLookup.TryGetValue(fid, out var field);

            object? GetValue((IReadOnlyDictionary<string, object?> Row, IReadOnlyDictionary<long, object?> Computed) p)
            {
                if (field != null && FormulaTypeMap.IsComputedField(field.TypeCode, field.Settings))
                    return p.Computed.TryGetValue(fid, out var cv) ? cv : null;
                if (field?.IsSystem == true && field.PhysicalColumnName != null)
                    return p.Row.TryGetValue(field.PhysicalColumnName, out var sv) ? sv : null;
                var col = PhysicalNaming.ColumnName((int)fid);
                return p.Row.TryGetValue(col, out var v) ? v : null;
            }

            if (ordered == null)
                ordered = desc ? pairs.OrderByDescending(GetValue, NullSafeComparer.Instance)
                               : pairs.OrderBy(GetValue, NullSafeComparer.Instance);
            else
                ordered = desc ? ordered.ThenByDescending(GetValue, NullSafeComparer.Instance)
                               : ordered.ThenBy(GetValue, NullSafeComparer.Instance);
        }

        return ordered?.ToList() ?? pairs.ToList();
    }

    // ── Private ─────────────────────────────────────────────────────────────────

    private static FilterGroup? StripFormulaNodes(
        FilterGroup group, HashSet<long> formulaFids, List<FilterCondition> collected)
    {
        var kept = new List<FilterNode>();
        foreach (var node in group.Nodes)
        {
            if (node.Condition != null)
            {
                if (formulaFids.Contains(node.Condition.FieldId))
                    collected.Add(node.Condition);
                else
                    kept.Add(node);
            }
            else if (node.Group != null)
            {
                var sub = StripFormulaNodes(node.Group, formulaFids, collected);
                if (sub != null)
                    kept.Add(new FilterNode { Group = sub });
            }
        }
        return kept.Count > 0 ? new FilterGroup { Logic = group.Logic, Nodes = kept } : null;
    }

    private static bool MatchesCondition(IReadOnlyDictionary<long, object?> computed, FilterCondition c)
    {
        computed.TryGetValue(c.FieldId, out var val);

        return c.Operator switch
        {
            "isEmpty"       => val is null || val.ToString() == string.Empty,
            "isNotEmpty"    => val is not null && val.ToString() != string.Empty,
            "eq"            => CompareValues(val, c.Value) == 0,
            "ne"            => CompareValues(val, c.Value) != 0,
            "gt"            => CompareValues(val, c.Value) > 0,
            "gte"           => CompareValues(val, c.Value) >= 0,
            "lt"            => CompareValues(val, c.Value) < 0,
            "lte"           => CompareValues(val, c.Value) <= 0,
            "contains"      => val?.ToString()?.Contains(c.Value ?? string.Empty, StringComparison.OrdinalIgnoreCase) == true,
            "notContains"   => val?.ToString()?.Contains(c.Value ?? string.Empty, StringComparison.OrdinalIgnoreCase) != true,
            "startsWith"    => val?.ToString()?.StartsWith(c.Value ?? string.Empty, StringComparison.OrdinalIgnoreCase) == true,
            "notStartsWith" => val?.ToString()?.StartsWith(c.Value ?? string.Empty, StringComparison.OrdinalIgnoreCase) != true,
            "date_eq"       => val is DateTime dt && DateTime.TryParse(c.Value, out var dv) && dt.Date == dv.Date,
            "in"            => ParseValueList(c.Value).Any(v => CompareValues(val, v) == 0),
            "notIn"         => !ParseValueList(c.Value).Any(v => CompareValues(val, v) == 0),
            _               => true,
        };
    }

    /// <summary>Mirrors RecordRepository.ParseValueList — the "in"/"notIn" wire format is a JSON
    /// string array in FilterCondition.Value, falling back to a comma split.</summary>
    private static List<string> ParseValueList(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return [];
        try
        {
            var arr = JsonSerializer.Deserialize<List<string>>(raw);
            if (arr != null) return arr.Where(v => !string.IsNullOrEmpty(v)).ToList();
        }
        catch (JsonException) { /* not JSON — fall through to comma split */ }
        return raw.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).ToList();
    }

    private static int CompareValues(object? a, string? b)
    {
        if (a is null && b is null) return 0;
        if (a is null) return -1;
        if (b is null) return 1;

        if (a is double d && double.TryParse(b, System.Globalization.NumberStyles.Any,
                System.Globalization.CultureInfo.InvariantCulture, out var db))
            return d.CompareTo(db);

        if (a is decimal dec && decimal.TryParse(b, out var decb))
            return dec.CompareTo(decb);

        if (a is DateTime dt && DateTime.TryParse(b, out var dtb))
            return dt.CompareTo(dtb);

        if (a is bool bl && bool.TryParse(b, out var blb))
            return bl.CompareTo(blb);

        return string.Compare(a.ToString(), b, StringComparison.OrdinalIgnoreCase);
    }
}

internal sealed class NullSafeComparer : IComparer<object?>
{
    public static readonly NullSafeComparer Instance = new();

    public int Compare(object? x, object? y)
    {
        if (x is null && y is null) return 0;
        if (x is null) return -1;
        if (y is null) return 1;
        if (x is IComparable cx)
        {
            try { return cx.CompareTo(y); }
            catch { /* type mismatch — fall through to string comparison */ }
        }
        return string.Compare(x.ToString(), y.ToString(), StringComparison.OrdinalIgnoreCase);
    }
}
